# Generated by Django 2.2 on 2019-05-20 22:36

from django.db import migrations, models
import scrawls.models


class Migration(migrations.Migration):

    dependencies = [
        ('scrawls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='expires_at',
            field=models.DateTimeField(default=scrawls.models.expiration_date),
        ),
    ]
