# Generated by Django 2.2.1 on 2019-05-25 23:30

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrawls', '0003_auto_20190524_0306'),
    ]

    operations = [
        migrations.AddField(
            model_name='wall',
            name='point',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
    ]
